### ISSUE TITLE
How to start the demo? I click contact device no effect.

### ISSUE THREAD

**Issue by qcscofield** [kdrag0n/fastboot.js#12]

**Comment by kdrag0n** [comment]
Clicking "Connect device" should open your browser's USB device selection prompt. If nothing happens, your browser either doesn't support WebUSB (only modern versions of Chromium do) or it doesn't work correctly on your platform (which might be possible if you're using Chromium on old versions of Android). It might also be caused by a modified version of Chromium that unintentionally broke WebUSB support.

Regardless of the cause, I can't do much about the issue in those cases because it's on the browser side. You can try one of the official WebUSB demos at https://webusb.github.io/arduino/demos/console/ to confirm this.
