### ISSUE TITLE
boot image error

### ISSUE THREAD

**Issue by Zibri** [kdrag0n/fastboot.js#24]
Uncaught (in promise) TypeError: device.bootBlob is not a function
    at HTMLFormElement.bootFormFile (ui.js:45:18)
    
the image works on fastoot ran from any OS..
not from this.

also: fastboot commands are separated by a colon.
so the string in command input should have a replace of " " with ":"

**Comment by kdrag0n** [comment]
Just updated the dist builds so it should work now.

Re command formats: replacing ` ` with `:` doesn't always work. It's true for flash commands but `reboot bootloader` is `reboot-bootloader` and OEM commands keep their spaces.

It's possible that some of this could be special-cased, but in general I think there should still be a raw command interface because of these differences.

**Comment by kdrag0n** [comment]
IMO the top-level commands should each be methods if we want a high-level command interface.

**Comment by Zibri** [comment]
Confirmed: it works now.
